### PR TITLE
Add Sencha Cmd to path if available

### PR DESCRIPTION
**Pull request by henning-cg**
For Sencha based projects we need to setup the environment with Sencha Cmd available on the path (Sencha Cmd is Sencha's tooling, similar to the combo npm/bower/gulp)

### CODE REVIEW

**Comment by hohwille** [comment]
Fine for me. However, as suggestion and discussion: We could also provide a simple convention for a file in a software folder that will be sourced if present. Then we do not have to tweak the central script for every custom tool. Instead we just provide scripts in each software tool folder:
e.g. for each ```SOFTWARE_PATH/*/ide-config[.bat]``` source that script. Then we can create a place where such scripts can be collected for various tools like sencha, node.js, etc.

**Comment by hohwille** [comment]
In your diff we can see that this seems to be related to sencha version 3. If someone later wants to use version 4 while others still want to use 3.x we get in trouble with updates of the script-package.

**Comment by henning-cg** [comment]
Actually, Sencha Cmd is currently at version 5. This variable seems to be some kind of marker for them introduced in version 3 but not necessarily indicating version 3.

But you are right that this can create conflicts in the future.

I like your suggestion of custom scripts inside the software folder, and was in fact thinking about something similar.

If it's fine for you, I will update this PR to start using this system.

**Comment by hohwille** [comment]
> If it's fine for you, I will update this PR to start using this system.

sounds great if you can find the time :)

**Comment by henning-cg** [comment]
Converted environment-project[.bat] to look for ide-config[.bat] files inside software installation folders

**Comment by henning-cg** [comment]
@hohwille Have you had a chance to look at this PR (it now supports custom ide-config.bat scripts inside software folder, to keep core oasp4j-ide clean, as you suggested.

**Comment by hohwille** [comment]
Sorry - quite busy at the moment and no other resources to delegate from my side. This one is not as easy. E.g. for backward compatibility we should keep the old nodejs feature if there is no such new script present the old behavior is kept and a legacy warning is prompted. Otherwise we will break existing installations for users that just update the scripts package. We can remove the legacy stuff some releases later.

**Comment by henning-cg** [comment]
@hohwille For now I do not touch the node.js part, it is still configured as it was before.

I just added the ability to load custom configure scripts, so we can use it for Sencha Cmd.

I agree that in the future we might do the same for node.js, and then the legacy warning as you mentioned will probably be needed.

But as it is right now, this PR will not cause problems, as it only changes behaviour if you have a software package with a ide-config script present.

We need this for devon, so it would be great if we could include this in the next release of oasp4j-ide.

**Comment by hohwille** [comment]
you are right. I was to stupid to read the diff properly as it looks missleading:

    -if [ -d "$SOFTWARE_PATH/nodejs" ]; then
    -  export PATH=$SOFTWARE_PATH/nodejs/bin:$PATH
    -fi
    +for i in `find $SOFTWARE_PATH -maxdepth 1 ! -path $SOFTWARE_PATH`; do
    +    if [ -d "$i/bin" ]; then
    ...

**Comment by hohwille** [comment]
Fine but two things to improve:
```export PATH=`npm bin -g`:$PATH```
This will not work reliable as it can prompt a result such as this:
> /home/hohwille/.npm
(not in PATH env variable)

So it is not only the path itself but additional clutter that will then break the ```PATH``` - even though the doc says ```(just prints the bin folder)```.

Further a suggestion for simplification:
> for i in `find $SOFTWARE_PATH -maxdepth 1 ! -path $SOFTWARE_PATH`; do

could be changed to 
> for i in `$SOFTWARE_PATH/*`; do

or am I missing something?

**Comment by henning-cg** [comment]
I wasn't aware of the npm behaviour, but it seems that it prints the warning message on STDERR, while the backticks only return STDOUT, so that should work fine.

Regarding the software search expression, good one :smiley: , definitely easier. I just added another commit containing this simplification.

**Comment by hohwille** [comment]
:+1: thanks @henning-cg

**Pull request merged**
